// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMPRESSEDVIDEO_FOXGLOVE_H_
#define FLATBUFFERS_GENERATED_COMPRESSEDVIDEO_FOXGLOVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "Time_generated.h"

namespace foxglove {

struct CompressedVideo;
struct CompressedVideoBuilder;

inline const ::flatbuffers::TypeTable *CompressedVideoTypeTable();

/// A single frame of a compressed video bitstream
struct CompressedVideo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CompressedVideoBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CompressedVideoTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_FRAME_ID = 6,
    VT_DATA = 8,
    VT_FORMAT = 10
  };
  /// Timestamp of video frame
  const foxglove::Time *timestamp() const {
    return GetStruct<const foxglove::Time *>(VT_TIMESTAMP);
  }
  /// Frame of reference for the video.
  /// 
  /// The origin of the frame is the optical center of the camera. +x points to the right in the video, +y points down, and +z points into the plane of the video.
  const ::flatbuffers::String *frame_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FRAME_ID);
  }
  /// Compressed video frame data.
  /// 
  /// For packet-based video codecs this data must begin and end on packet boundaries (no partial packets), and must contain enough video packets to decode exactly one image (either a keyframe or delta frame). Note: Foxglove does not support video streams that include B frames because they require lookahead.
  /// 
  /// Specifically, the requirements for different `format` values are:
  /// 
  /// - `h264`
  ///   - Use Annex B formatted data
  ///   - Each CompressedVideo message should contain enough NAL units to decode exactly one video frame
  ///   - Each message containing a key frame (IDR) must also include a SPS NAL unit
  /// 
  /// - `h265` (HEVC)
  ///   - Use Annex B formatted data
  ///   - Each CompressedVideo message should contain enough NAL units to decode exactly one video frame
  ///   - Each message containing a key frame (IRAP) must also include relevant VPS/SPS/PPS NAL units
  /// 
  /// - `vp9`
  ///   - Each CompressedVideo message should contain exactly one video frame
  /// 
  /// - `av1`
  ///   - Use the "Low overhead bitstream format" (section 5.2)
  ///   - Each CompressedVideo message should contain enough OBUs to decode exactly one video frame
  ///   - Each message containing a key frame must also include a Sequence Header OBU
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  /// Video format.
  /// 
  /// Supported values: `h264`, `h265`, `vp9`, `av1`.
  /// 
  /// Note: compressed video support is subject to hardware limitations and patent licensing, so not all encodings may be supported on all platforms. See more about [H.265 support](https://caniuse.com/hevc), [VP9 support](https://caniuse.com/webm), and [AV1 support](https://caniuse.com/av1).
  const ::flatbuffers::String *format() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FORMAT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<foxglove::Time>(verifier, VT_TIMESTAMP, 4) &&
           VerifyOffset(verifier, VT_FRAME_ID) &&
           verifier.VerifyString(frame_id()) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyOffset(verifier, VT_FORMAT) &&
           verifier.VerifyString(format()) &&
           verifier.EndTable();
  }
};

struct CompressedVideoBuilder {
  typedef CompressedVideo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(const foxglove::Time *timestamp) {
    fbb_.AddStruct(CompressedVideo::VT_TIMESTAMP, timestamp);
  }
  void add_frame_id(::flatbuffers::Offset<::flatbuffers::String> frame_id) {
    fbb_.AddOffset(CompressedVideo::VT_FRAME_ID, frame_id);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(CompressedVideo::VT_DATA, data);
  }
  void add_format(::flatbuffers::Offset<::flatbuffers::String> format) {
    fbb_.AddOffset(CompressedVideo::VT_FORMAT, format);
  }
  explicit CompressedVideoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CompressedVideo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CompressedVideo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CompressedVideo> CreateCompressedVideo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const foxglove::Time *timestamp = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> frame_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0,
    ::flatbuffers::Offset<::flatbuffers::String> format = 0) {
  CompressedVideoBuilder builder_(_fbb);
  builder_.add_format(format);
  builder_.add_data(data);
  builder_.add_frame_id(frame_id);
  builder_.add_timestamp(timestamp);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CompressedVideo> CreateCompressedVideoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const foxglove::Time *timestamp = nullptr,
    const char *frame_id = nullptr,
    const std::vector<uint8_t> *data = nullptr,
    const char *format = nullptr) {
  auto frame_id__ = frame_id ? _fbb.CreateString(frame_id) : 0;
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  auto format__ = format ? _fbb.CreateString(format) : 0;
  return foxglove::CreateCompressedVideo(
      _fbb,
      timestamp,
      frame_id__,
      data__,
      format__);
}

inline const ::flatbuffers::TypeTable *CompressedVideoTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 1, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    foxglove::TimeTypeTable
  };
  static const char * const names[] = {
    "timestamp",
    "frame_id",
    "data",
    "format"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const foxglove::CompressedVideo *GetCompressedVideo(const void *buf) {
  return ::flatbuffers::GetRoot<foxglove::CompressedVideo>(buf);
}

inline const foxglove::CompressedVideo *GetSizePrefixedCompressedVideo(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<foxglove::CompressedVideo>(buf);
}

inline bool VerifyCompressedVideoBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<foxglove::CompressedVideo>(nullptr);
}

inline bool VerifySizePrefixedCompressedVideoBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<foxglove::CompressedVideo>(nullptr);
}

inline void FinishCompressedVideoBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::CompressedVideo> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCompressedVideoBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::CompressedVideo> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace foxglove

#endif  // FLATBUFFERS_GENERATED_COMPRESSEDVIDEO_FOXGLOVE_H_
