// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DURATION_FOXGLOVE_H_
#define FLATBUFFERS_GENERATED_DURATION_FOXGLOVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace foxglove {

struct Duration;

inline const ::flatbuffers::TypeTable *DurationTypeTable();

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Duration FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t sec_;
  int32_t nsec_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DurationTypeTable();
  }
  Duration()
      : sec_(0),
        nsec_(0) {
  }
  Duration(int32_t _sec, int32_t _nsec)
      : sec_(::flatbuffers::EndianScalar(_sec)),
        nsec_(::flatbuffers::EndianScalar(_nsec)) {
  }
  /// Signed seconds of the span of time. Must be from -315,576,000,000 to +315,576,000,000 inclusive.
  int32_t sec() const {
    return ::flatbuffers::EndianScalar(sec_);
  }
  /// if sec === 0 : -999,999,999 <= nsec <= +999,999,999
  /// otherwise sign of sec must match sign of nsec or be 0 and abs(nsec) <= 999,999,999
  int32_t nsec() const {
    return ::flatbuffers::EndianScalar(nsec_);
  }
};
FLATBUFFERS_STRUCT_END(Duration, 8);

inline const ::flatbuffers::TypeTable *DurationTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_INT, 0, -1 },
    { ::flatbuffers::ET_INT, 0, -1 }
  };
  static const int64_t values[] = { 0, 4, 8 };
  static const char * const names[] = {
    "sec",
    "nsec"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 2, type_codes, nullptr, nullptr, values, names
  };
  return &tt;
}

}  // namespace foxglove

#endif  // FLATBUFFERS_GENERATED_DURATION_FOXGLOVE_H_
