// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RAWAUDIO_FOXGLOVE_H_
#define FLATBUFFERS_GENERATED_RAWAUDIO_FOXGLOVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "Time_generated.h"

namespace foxglove {

struct RawAudio;
struct RawAudioBuilder;

inline const ::flatbuffers::TypeTable *RawAudioTypeTable();

/// A single block of an audio bitstream
struct RawAudio FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RawAudioBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return RawAudioTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_DATA = 6,
    VT_FORMAT = 8,
    VT_SAMPLE_RATE = 10,
    VT_NUMBER_OF_CHANNELS = 12
  };
  /// Timestamp of the start of the audio block
  const foxglove::Time *timestamp() const {
    return GetStruct<const foxglove::Time *>(VT_TIMESTAMP);
  }
  /// Audio data. The samples in the data must be interleaved and little-endian
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  /// Audio format. Only 'pcm-s16' is currently supported
  const ::flatbuffers::String *format() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FORMAT);
  }
  /// Sample rate in Hz
  uint32_t sample_rate() const {
    return GetField<uint32_t>(VT_SAMPLE_RATE, 0);
  }
  /// Number of channels in the audio block
  uint32_t number_of_channels() const {
    return GetField<uint32_t>(VT_NUMBER_OF_CHANNELS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<foxglove::Time>(verifier, VT_TIMESTAMP, 4) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyOffset(verifier, VT_FORMAT) &&
           verifier.VerifyString(format()) &&
           VerifyField<uint32_t>(verifier, VT_SAMPLE_RATE, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUMBER_OF_CHANNELS, 4) &&
           verifier.EndTable();
  }
};

struct RawAudioBuilder {
  typedef RawAudio Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(const foxglove::Time *timestamp) {
    fbb_.AddStruct(RawAudio::VT_TIMESTAMP, timestamp);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(RawAudio::VT_DATA, data);
  }
  void add_format(::flatbuffers::Offset<::flatbuffers::String> format) {
    fbb_.AddOffset(RawAudio::VT_FORMAT, format);
  }
  void add_sample_rate(uint32_t sample_rate) {
    fbb_.AddElement<uint32_t>(RawAudio::VT_SAMPLE_RATE, sample_rate, 0);
  }
  void add_number_of_channels(uint32_t number_of_channels) {
    fbb_.AddElement<uint32_t>(RawAudio::VT_NUMBER_OF_CHANNELS, number_of_channels, 0);
  }
  explicit RawAudioBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RawAudio> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RawAudio>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RawAudio> CreateRawAudio(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const foxglove::Time *timestamp = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0,
    ::flatbuffers::Offset<::flatbuffers::String> format = 0,
    uint32_t sample_rate = 0,
    uint32_t number_of_channels = 0) {
  RawAudioBuilder builder_(_fbb);
  builder_.add_number_of_channels(number_of_channels);
  builder_.add_sample_rate(sample_rate);
  builder_.add_format(format);
  builder_.add_data(data);
  builder_.add_timestamp(timestamp);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RawAudio> CreateRawAudioDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const foxglove::Time *timestamp = nullptr,
    const std::vector<uint8_t> *data = nullptr,
    const char *format = nullptr,
    uint32_t sample_rate = 0,
    uint32_t number_of_channels = 0) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  auto format__ = format ? _fbb.CreateString(format) : 0;
  return foxglove::CreateRawAudio(
      _fbb,
      timestamp,
      data__,
      format__,
      sample_rate,
      number_of_channels);
}

inline const ::flatbuffers::TypeTable *RawAudioTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 1, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    foxglove::TimeTypeTable
  };
  static const char * const names[] = {
    "timestamp",
    "data",
    "format",
    "sample_rate",
    "number_of_channels"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 5, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const foxglove::RawAudio *GetRawAudio(const void *buf) {
  return ::flatbuffers::GetRoot<foxglove::RawAudio>(buf);
}

inline const foxglove::RawAudio *GetSizePrefixedRawAudio(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<foxglove::RawAudio>(buf);
}

inline bool VerifyRawAudioBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<foxglove::RawAudio>(nullptr);
}

inline bool VerifySizePrefixedRawAudioBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<foxglove::RawAudio>(nullptr);
}

inline void FinishRawAudioBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::RawAudio> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRawAudioBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::RawAudio> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace foxglove

#endif  // FLATBUFFERS_GENERATED_RAWAUDIO_FOXGLOVE_H_
