// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SPHEREPRIMITIVE_FOXGLOVE_H_
#define FLATBUFFERS_GENERATED_SPHEREPRIMITIVE_FOXGLOVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "Color_generated.h"
#include "Pose_generated.h"
#include "Vector3_generated.h"

namespace foxglove {

struct SpherePrimitive;
struct SpherePrimitiveBuilder;

inline const ::flatbuffers::TypeTable *SpherePrimitiveTypeTable();

/// A primitive representing a sphere or ellipsoid
struct SpherePrimitive FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SpherePrimitiveBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SpherePrimitiveTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSE = 4,
    VT_SIZE = 6,
    VT_COLOR = 8
  };
  /// Position of the center of the sphere and orientation of the sphere
  const foxglove::Pose *pose() const {
    return GetPointer<const foxglove::Pose *>(VT_POSE);
  }
  /// Size (diameter) of the sphere along each axis
  const foxglove::Vector3 *size() const {
    return GetPointer<const foxglove::Vector3 *>(VT_SIZE);
  }
  /// Color of the sphere
  const foxglove::Color *color() const {
    return GetPointer<const foxglove::Color *>(VT_COLOR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POSE) &&
           verifier.VerifyTable(pose()) &&
           VerifyOffset(verifier, VT_SIZE) &&
           verifier.VerifyTable(size()) &&
           VerifyOffset(verifier, VT_COLOR) &&
           verifier.VerifyTable(color()) &&
           verifier.EndTable();
  }
};

struct SpherePrimitiveBuilder {
  typedef SpherePrimitive Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pose(::flatbuffers::Offset<foxglove::Pose> pose) {
    fbb_.AddOffset(SpherePrimitive::VT_POSE, pose);
  }
  void add_size(::flatbuffers::Offset<foxglove::Vector3> size) {
    fbb_.AddOffset(SpherePrimitive::VT_SIZE, size);
  }
  void add_color(::flatbuffers::Offset<foxglove::Color> color) {
    fbb_.AddOffset(SpherePrimitive::VT_COLOR, color);
  }
  explicit SpherePrimitiveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SpherePrimitive> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SpherePrimitive>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SpherePrimitive> CreateSpherePrimitive(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<foxglove::Pose> pose = 0,
    ::flatbuffers::Offset<foxglove::Vector3> size = 0,
    ::flatbuffers::Offset<foxglove::Color> color = 0) {
  SpherePrimitiveBuilder builder_(_fbb);
  builder_.add_color(color);
  builder_.add_size(size);
  builder_.add_pose(pose);
  return builder_.Finish();
}

inline const ::flatbuffers::TypeTable *SpherePrimitiveTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 2 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    foxglove::PoseTypeTable,
    foxglove::Vector3TypeTable,
    foxglove::ColorTypeTable
  };
  static const char * const names[] = {
    "pose",
    "size",
    "color"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const foxglove::SpherePrimitive *GetSpherePrimitive(const void *buf) {
  return ::flatbuffers::GetRoot<foxglove::SpherePrimitive>(buf);
}

inline const foxglove::SpherePrimitive *GetSizePrefixedSpherePrimitive(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<foxglove::SpherePrimitive>(buf);
}

inline bool VerifySpherePrimitiveBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<foxglove::SpherePrimitive>(nullptr);
}

inline bool VerifySizePrefixedSpherePrimitiveBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<foxglove::SpherePrimitive>(nullptr);
}

inline void FinishSpherePrimitiveBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::SpherePrimitive> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSpherePrimitiveBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::SpherePrimitive> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace foxglove

#endif  // FLATBUFFERS_GENERATED_SPHEREPRIMITIVE_FOXGLOVE_H_
